server:
  port: 8010
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    healthcheck:
      enabled: true
spring:
  application:
    name: movie-service
