server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  application:
    name: user-service
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

management:
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    healthcheck:
      enabled: true
  instance:
    metadata-map:
      provider-metadata: 用户服务的metadata
